import type { CarSuggestion } from "./types";

// Stage 1 placeholder data. In Stage 2 this gets replaced by the parsed
// JSON response from the AI call, using the exact same CarSuggestion shape.
export const MOCK_SUGGESTIONS: CarSuggestion[] = [
  {
    id: "1",
    make: "BMW",
    model: "M240i Coupe",
    year: 2024,
    priceEUR: 58900,
    bodyType: "Coupe",
    horsepower: 374,
    fuelType: "Petrol",
    zeroToHundredSec: 4.3,
    imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2025-bmw-2-series-coupe-113-6669ddf419a7f.jpg?crop=1.00xw:0.453xh;0,0.322xh&resize=1200:*",
    reason:
      "Συνδυάζει σπορ οδηγική εμπειρία, καλή ισχύ (374 hp) και τιμή κάτω από το budget σου, με ευέλικτο 6κύλινδρο κινητήρα."
  },
  {
    id: "2",
    make: "Audi",
    model: "S3 Sportback",
    year: 2024,
    priceEUR: 52500,
    bodyType: "Hatchback",
    horsepower: 310,
    fuelType: "Petrol",
    zeroToHundredSec: 4.8,
    imageUrl: "https://cdn.motor1.com/images/mgl/ZnKRXz/s3/manhart-s-400-basis-audi-s3-limousine.jpg",
    reason:
      "Compact sport hatchback με quattro τετρακίνηση, ιδανικό για καθημερινή χρήση χωρίς να θυσιάζεις τις επιδόσεις.",
  },
  {
    id: "3",
    make: "Ford",
    model: "Mustang GT",
    year: 2023,
    priceEUR: 54900,
    bodyType: "Coupe",
    horsepower: 449,
    fuelType: "Petrol",
    zeroToHundredSec: 4.5,
    imageUrl: "https://images.jazelc.com/uploads/brandonfordtampa-m2en/What-Are-the-Ford-Mustang-GTD-Liquid-Carbon-Features-1200x675_oem.jpg",
    reason:
      "Καθαρόαιμο muscle car εμπειρία με V8 ήχο, δίνει τη μεγαλύτερη ισχύ της λίστας εντός budget.",

  },
  {
    id: "4",
    make: "Toyota",
    model: "Yaris",
    year: 2023,
    priceEUR: 19500,
    bodyType: "Hatchback",
    horsepower: 72,
    fuelType: "Petrol",
    zeroToHundredSec: 14.6,
    imageUrl: "https://images.carsguide.com.au/image/upload/e_trim:10,f_auto,c_scale,t_cg_base,w_678/v1/editorial/vhs/2025-Toyota-Yaris-Hybrid-1490x790--(1).png",
    reason: "Οικονομικό και αξιόπιστο, ιδανικό για πόλη και νέους οδηγούς.",
  },
  {
    id: "5",
    make: "Volkswagen",
    model: "Polo",
    year: 2023,
    priceEUR: 21900,
    bodyType: "Hatchback",
    horsepower: 95,
    fuelType: "Petrol",
    zeroToHundredSec: 10.8,
    imageUrl: "https://www.onlineauto.com.au/contentAsset/image/f146d27c829a47b0731e42d9a278cda3",
    reason: "Ποιοτικό μικρό hatchback με χαμηλή κατανάλωση και άνετο σαλόνι.",
  },
  {
    id: "6",
    make: "Suzuki",
    model: "Swift",
    year: 2023,
    priceEUR: 17900,
    bodyType: "Hatchback",
    horsepower: 83,
    fuelType: "Hybrid",
    zeroToHundredSec: 12.2,
    imageUrl: "https://media.umbraco.io/suzuki-gb/smtlqp3h/image53.png",
    reason: "Ελαφρύ, ευέλικτο και ήπια υβριδικό — πολύ χαμηλά έξοδα χρήσης.",
  },
  {
    id: "7",
    make: "Peugeot",
    model: "308 BlueHDi",
    year: 2023,
    priceEUR: 28500,
    bodyType: "Hatchback",
    horsepower: 130,
    fuelType: "Diesel",
    zeroToHundredSec: 10.6,
    imageUrl: "https://images.carsguide.com.au/image/upload/e_trim:10,f_auto,c_scale,t_cg_base,w_678/v1/editorial/vhs/2025-Peugeot-308-Hatch-1490x790--(1).png",
    reason: "Diesel με πολύ χαμηλή κατανάλωση, ιδανικό για μεγάλα ταξίδια.",
  },
  {
    id: "8",
    make: "Tesla",
    model: "Model 3 Performance",
    year: 2024,
    priceEUR: 55990,
    bodyType: "Sedan",
    horsepower: 460,
    fuelType: "Electric",
    zeroToHundredSec: 3.1,
    imageUrl: "https://cdn.gcdata.gr/c3/p_1920_1811068.webp",
    reason: "Ηλεκτρικό με εκρηκτική επιτάχυνση και μηδενικά καύσιμα.",
  },
  {
    id: "9",
    make: "Hyundai",
    model: "Tucson Hybrid",
    year: 2024,
    priceEUR: 36900,
    bodyType: "SUV",
    horsepower: 230,
    fuelType: "Hybrid",
    zeroToHundredSec: 8.0,
    imageUrl: "https://images.carsguide.com.au/image/upload/e_trim:10,f_auto,c_scale,t_cg_base,w_678/v1/editorial/vhs/2025-Hyundai-Tucson-Hybrid-1490x790--(1).png",
    reason: "Οικογενειακό SUV με υβριδική οικονομία και πλούσιο εξοπλισμό.",
  },
  {
    id: "10",
    make: "Mazda",
    model: "MX-5",
    year: 2023,
    priceEUR: 33500,
    bodyType: "Convertible",
    horsepower: 184,
    fuelType: "Petrol",
    zeroToHundredSec: 6.5,
    imageUrl: "https://images.carsguide.com.au/image/upload/e_trim:10,f_auto,c_scale,t_cg_base,w_678/v1/editorial/vhs/2025-Mazda-MX-5-1490x790--(1).png",
    reason: "Το πιο διασκεδαστικό roadster — ελαφρύ, ανοιχτό, καθαρή οδήγηση.",
  },
  {
    id: "11",
    make: "Skoda",
    model: "Octavia Wagon",
    year: 2023,
    priceEUR: 27900,
    bodyType: "Wagon",
    horsepower: 116,
    fuelType: "Diesel",
    zeroToHundredSec: 10.3,
    imageUrl: "https://images.carsguide.com.au/image/upload/e_trim:10,f_auto,c_scale,t_cg_base,w_678/v1/editorial/vhs/2025-Skoda-Octavia-Wagon-1490x790--(1).png",
    reason: "Τεράστιος χώρος αποσκευών με diesel οικονομία — ο βασιλιάς της πρακτικότητας.",
  },
];
